# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181017_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
